### ISSUE TITLE
Incorporate TypeScript in the project

### ISSUE THREAD

**Issue by kiranjd** [kiranjd/rn-animation#1]
This might involve porting some existing code to TS as well on top of configuring TS only project.

Sukshith, let me know if you need help with that

**Comment by kiranjd** [comment]
@Sukshith27 Have you had time to tackle this?

**Comment by Sukshith27** [comment]
All the issues has been resolved after adding TS

**Comment by kiranjd** [comment]
Could you issue a PR to master?

**Comment by Sukshith27** [comment]
No, will do that later

**Comment by Sukshith27** [comment]
PR made to master
